# Generated by Django 4.2.30 on 2026-04-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('avg_wait_minutes', models.FloatField(default=0)),
                ('throughput', models.PositiveIntegerField(default=0)),
                ('abandonment_rate', models.FloatField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_records', to='queues.service')),
            ],
            options={
                'indexes': [models.Index(fields=['service', 'period_start'], name='analytics_a_service_5a09b9_idx')],
            },
        ),
    ]
