# Generated by Django 5.2.14 on 2026-05-12 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_queue_public_id_queue_last_token_issued_queueentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
