# Generated by Django 5.2.14 on 2026-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_queue_image_and_name_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='queue',
            new_name='queues_queu_organiz_62007a_idx',
            old_name='queues_queu_organiz_0a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='queue',
            new_name='queues_queu_name_72e595_idx',
            old_name='queues_queue_name_idx',
        ),
        migrations.RenameIndex(
            model_name='queueentry',
            new_name='queues_queu_queue_i_90b16e_idx',
            old_name='queues_queu_queue_i_8e2f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='queueentry',
            new_name='queues_queu_queue_i_440841_idx',
            old_name='queues_queu_queue_i_9c3b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='queueentry',
            new_name='queues_queu_queue_i_60d166_idx',
            old_name='queues_queu_queue_i_a1d4f3_idx',
        ),
    ]
