# Generated by Django 5.2.14 on 2026-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyorganizationmetric',
            new_name='reports_dai_organiz_96c6fc_idx',
            old_name='reports_dai_organiz_9e5f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyorganizationmetric',
            new_name='reports_dai_date_afe7eb_idx',
            old_name='reports_dai_date_0b7c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyqueuemetric',
            new_name='reports_dai_queue_i_4ecfc8_idx',
            old_name='reports_dai_queue_i_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyqueuemetric',
            new_name='reports_dai_date_409915_idx',
            old_name='reports_dai_date_8d3e4f_idx',
        ),
    ]
