# Generated by Django 4.2.30 on 2026-04-20 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=32)),
                ('average_service_minutes', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20)),
                ('position', models.PositiveIntegerField(default=1)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='queues.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(db_index=True, max_length=12)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='organizations.agentcounter')),
                ('queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='queues.queueentry')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='queues_tick_token_05568d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'is_active'], name='queues_serv_organiz_f9fb6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['service', 'status', 'created_at'], name='queues_queu_service_488fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['user', 'status'], name='queues_queu_user_id_e440e3_idx'),
        ),
    ]
